### ISSUE TITLE
`+` operator on a depset is forbidden

### ISSUE THREAD

**Issue by regisd** [ProdriveTechnologies/bazel-pandoc#6]
With pandoc rule v0.2, I encounter:

ERROR: in _pandoc rule:
> 	File "/private/var/tmp/_bazel_regisd/06f542c1a539b08f2925af301e3c7ab9/external/bazel_pandoc/pandoc.bzl", line 3, in _pandoc_impl
> 		ctx.actions.run(<5 more arguments>)
> 	File "/private/var/tmp/_bazel_regisd/06f542c1a539b08f2925af301e3c7ab9/external/bazel_pandoc/pandoc.bzl", line 15, in ctx.actions.run
> 		toolchain.pandoc.files + ctx.files.src
> `+` operator on a depset is forbidden. See https://docs.bazel.build/versions/master/skylark/depsets.html for recommendations. Use --incompatible_depset_union=false to temporarily disable this check.

**Comment by regisd** [comment]
This is new with Bazel release 1.1.0

**Comment by patbro** [comment]
Resolved in PR #7
