### ISSUE TITLE
Pandoc version as parameter

### ISSUE THREAD

**Issue by kylecordes** [ProdriveTechnologies/bazel-pandoc#9]
Bravo(!) for designing these rules to supply pandoc; many Bazel rules out there make it the user's problem to have the underlying binaries in place on all build machines, creating opportunity for version skew and other ills.

But... the downside is that, for example here in this rule, it can be tough to keep up with versions of the underlying tool. It appears that `bazel-pandoc` is currently hardcoded to retrieve and use only Pandoc v2.3.1. Pandoc 2.8 just shipped, and there have been various other versions since 2.3.1.

**Therefore, a feature request**:

* Make `pandoc()` accept a version parameter
* Update `pandoc()` to know about recent versions

A downside of this approach: each new version of Pandoc requires a new `bazel-pandoc`. It is possible to work around that by allowing the user to supply a replacement mapping (from platform to URL+hash) so that a newer version of Pandoc can be used immediately with minor inconvenience. Such a mechanism can also be used by folks who have a requirement to fetch all tools from a blessed internal repository.

**Comment by patbro** [comment]
I believe we should just use the latest and greatest version of pandoc. So this only requires us to update `repositories.bzl`.

**Comment by regisd** [comment]
And pandoc is based on a `toolchain`. Assuming everything is set up correctly, you can use the version of your choice by changing the toolchain.
